namespace EvenFibonacciNumbers
{
    internal class Program
    {
        //Each new term in the Fibonacci sequence is generated by adding the previous two terms.By starting with 1 and 2, the first 10 terms Will be:
        //ı, 2, 3, 5, 8, 13, 21, 34, 55, 89,..
        //By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
        static void Main(string[] args)
        {
            int limit = 4000000;
            int sum = 0;
            int prev = 1;
            int current = 2;

            // Generate Fibonacci sequence
            while (current < limit)
            {
                // Check if the current term is even
                if (current % 2 == 0)
                {
                    sum += current;
                }

                // Generate the next term
                int next = prev + current;
                prev = current;
                current = next;
            }

            // Print the sum
            Console.WriteLine("Sum of even-valued terms in Fibonacci sequence up to 4 million: " + sum);

        }
    }
}
